package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/joho/godotenv"
	"github.com/pci-tamper-protect/traefik-cloudrun-provider/provider"
	"gopkg.in/yaml.v3"
)

const (
	defaultEnvironment = "stg"
	defaultRegion      = "us-central1"
	defaultOutputFile  = "/etc/traefik/dynamic/routes.yml"
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)
	fmt.Fprintf(os.Stderr, "🚀 Starting traefik-cloudrun-provider at %s\n", time.Now().UTC().Format(time.RFC3339))

	// Load .env file if it exists (optional, silently ignore if not found)
	if err := godotenv.Load(); err != nil {
		// Ignore file not found errors - .env is optional
		// Environment variables can be set directly in Cloud Run
		if !os.IsNotExist(err) {
			log.Printf("Warning: Error loading .env file: %v", err)
		}
	}

	// Load configuration from environment
	config := loadConfig()

	fmt.Fprintf(os.Stderr, "🔍 Generating Traefik routes from Cloud Run service labels...\n")
	fmt.Fprintf(os.Stderr, "   Environment: %s\n", config.Environment)
	fmt.Fprintf(os.Stderr, "   Projects: %v\n", config.ProjectIDs)
	fmt.Fprintf(os.Stderr, "   Region: %s\n", config.Region)
	fmt.Fprintf(os.Stderr, "   Output: %s\n", config.OutputFile)
	fmt.Fprintf(os.Stderr, "\n")

	// Create output directory
	if err := os.MkdirAll(getDir(config.OutputFile), 0755); err != nil {
		log.Fatalf("Failed to create output directory: %v", err)
	}

	// Create provider
	providerConfig := &provider.Config{
		ProjectIDs:   config.ProjectIDs,
		Region:       config.Region,
		PollInterval: 30 * time.Second, // Not used in one-shot mode
	}

	p, err := provider.New(providerConfig)
	if err != nil {
		log.Fatalf("Failed to create provider: %v", err)
	}

	// Generate configuration (one-shot, not continuous polling)
	configChan := make(chan *provider.DynamicConfig, 1)
	if err := p.Start(configChan); err != nil {
		log.Fatalf("Failed to start provider: %v", err)
	}

	// Wait for first configuration
	select {
	case dynamicConfig := <-configChan:
		// Write routes.yml
		if err := writeRoutes(config.OutputFile, dynamicConfig); err != nil {
			log.Fatalf("Failed to write routes file: %v", err)
		}

		fmt.Fprintf(os.Stderr, "\n✅ Routes file generated at %s\n", config.OutputFile)
		fmt.Fprintf(os.Stderr, "\n📊 Summary:\n")
		fmt.Fprintf(os.Stderr, "   Routers: %d\n", len(dynamicConfig.HTTP.Routers))
		fmt.Fprintf(os.Stderr, "   Services: %d\n", len(dynamicConfig.HTTP.Services))
		fmt.Fprintf(os.Stderr, "   Middlewares: %d\n", len(dynamicConfig.HTTP.Middlewares))

	case <-time.After(60 * time.Second):
		log.Fatalf("Timeout waiting for configuration")
	}

	// Stop provider
	if err := p.Stop(); err != nil {
		log.Printf("Warning: Failed to stop provider: %v", err)
	}
}

type AppConfig struct {
	Environment string
	ProjectIDs  []string
	Region      string
	OutputFile  string
}

func loadConfig() *AppConfig {
	env := os.Getenv("ENVIRONMENT")
	if env == "" {
		env = defaultEnvironment
	}

	var projectIDs []string

	// Primary project (required)
	primaryProject := os.Getenv("LABS_PROJECT_ID")
	if primaryProject == "" {
		log.Fatalf("LABS_PROJECT_ID environment variable is required")
	}
	projectIDs = append(projectIDs, primaryProject)

	// Secondary project (optional)
	secondaryProject := os.Getenv("HOME_PROJECT_ID")
	if secondaryProject != "" {
		projectIDs = append(projectIDs, secondaryProject)
	}

	region := os.Getenv("REGION")
	if region == "" {
		region = defaultRegion
	}

	outputFile := defaultOutputFile
	if len(os.Args) > 1 {
		outputFile = os.Args[1]
	}

	return &AppConfig{
		Environment: env,
		ProjectIDs:  projectIDs,
		Region:      region,
		OutputFile:  outputFile,
	}
}

func getDir(path string) string {
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '/' {
			return path[:i]
		}
	}
	return "."
}

func writeRoutes(outputFile string, config *provider.DynamicConfig) error {
	file, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	// Write header comment
	fmt.Fprintf(file, "# Auto-generated Traefik routes from Cloud Run service labels\n")
	fmt.Fprintf(file, "# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(file, "# Environment: %s\n", os.Getenv("ENVIRONMENT"))
	fmt.Fprintf(file, "#\n")
	fmt.Fprintf(file, "# This file is generated by traefik-cloudrun-provider\n")
	fmt.Fprintf(file, "# Labels follow the same format as docker-compose.yml\n\n")

	// Write YAML
	encoder := yaml.NewEncoder(file)
	encoder.SetIndent(2)
	if err := encoder.Encode(config); err != nil {
		return fmt.Errorf("failed to encode YAML: %w", err)
	}

	return encoder.Close()
}
