# Markdownlint configuration
# Documentation: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Multiple consecutive blank lines
MD012:
  maximum: 2

# Inline HTML
MD033: false

# First line in file should be a top level heading
MD041: false

# Emphasis used instead of a heading
MD036: false
